### PR TITLE
Debug UI fixes

### PR DESCRIPTION
**Pull request by LLeny**
Don't add watch if already exist
Allow multiple debug controls of allowed types
Apply breakpoints after reset
Enable/Disable breakpoints

### CODE REVIEW

**Comment by 42Bastian** [comment]
Did not check in detail, but does it allow "CPU" view of the memory? (using $fff7 to select bank)

**Comment by LLeny** [comment]
> Did not check in detail, but does it allow "CPU" view of the memory? (using $fff7 to select bank)

Sorry I am not sure to understand "CPU" view. 
Do you mean what's after fff8 ? The interrupt vectors addresses ? 
Or after messing with MAPCTL ?

**Comment by 42Bastian** [comment]
> > Did not check in detail, but does it allow "CPU" view of the memory? (using $fff7 to select bank)
> 
> Sorry I am not sure to understand "CPU" view. Do you mean what's after fff8 ? The interrupt vectors addresses ? Or after messing with MAPCTL ?

Right, after messing with MAPCTL.
So a pure Mikey, pure SUZY, pure RAM (that is SUZY's view) and a view a "lda $fxxx" would see.

**Comment by 42Bastian** [comment]
I agree that windows should remember its settings. One of the worst about handybug is to restore every thing after relaunching the emulator.
A Mikey \ Suzy only window is great. Just think about tinkering with the sound registers in an easier way.

**Comment by LLeny** [comment]
I believe then SysConfig would need to be refactored first for something simpler, more generic. The current manual string concat/parsing isn't extremely convenient to add dynamic configs.

**Comment by laoo** [comment]
> I believe then SysConfig would need to be refactored first for something simpler, more generic. The current manual string concat/parsing isn't extremely convenient to add dynamic configs.

I agree. It was initial approach for simple needs. How about XML? I can change it to pugi_xml reading/writing. I prefer XML as it's documenting itself (opposed to json).

**Comment by 42Bastian** [comment]
I'd say, since this is not the funniest part, you should go the way the easiest. So if you know XML handling in and out, go for it. But JSON is a pain. It is pure M2M.

**Pull request closed without merging**
